### ISSUE TITLE
Cloudinary API credentials exposed

### ISSUE THREAD

**Issue by nielsdB97** [Anacgbarreto/wdi-project-4-api#1]
Your (private) credentials for Cloudinary's API are currently hardcoded into your [application](https://github.com/Anacgbarreto/wdi-project-4-Alphabook/blob/master/server/index.js#L11).
This is not desirable, thus I would recommend moving them to _environment variables_.

This can be easily done with the [dotenv](http://npm.im/dotenv) package. Just make sure to add the `.env` file to your `.gitignore`.

**Comment by anagobarreto** [comment]
Thanks for flagging, this was just a practice project so didn't paid much attention. Removed it now.
